name: Project test 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}    
jobs:
  test:
    runs-on: ubuntu-latest
#    outputs:
#      output1: ${{ steps.start_time.outputs.test }}
#      output2: ${{ steps.stop_time.outputs.test }}
    steps:
        - id: start_time
          shell: bash
          run: echo "::set-output name=start_time::$(date)"
        - name: Checkout
          uses: actions/checkout@latest
        - name: Setup-node
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
      
        - name: Install
          run: npm ci

        - name: Run Test
          run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

        - name: Build
          run: npm build
        
        - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v1
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}  
        - id: stop_time
          shell: bash
          run: echo "::set-output name=stop_time::$(date)"
          
#  time:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
        - name: time
          run: echo ${{steps.start_time.outputs.start_time}} ${{steps.stop_time.outputs.stop_time}}
#  mail:
#    if: ${{ always() }}
#    needs: [test, time]
#    runs-on: ubuntu-latest
#    steps:
#        - name: Checkout
#          uses: actions/checkout@v2
#        - name: Setup-node
#          uses: actions/setup-node@v1
#          with:
#            node-version: 14.x
#Работает, но забанили за спам.
#Закомментил, т.к. мешает исполнению
        - name: Send mail
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.mail.ru
            server_port: 465
            username:  test.anaconda@mail.ru
            password: ${{ secrets.MAIL }}
            subject: Github pipeline
            to: gats1995@mail.ru
            from: GitHubTest
            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}. Time start ${{steps.start_time.outputs.start_time}}. Time stop ${{steps.stop_time.outputs.stop_time}}.
