name: Angular Actions pipeline
on:
  push:
    branches:
      - dev
      - 'feature/*'
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.end_timer.outputs.duration }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 

      - name: Start Timer
        id: start_timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Run Angular tests
        run: |
          cd angular
          npm install
          npm test --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
          
      - name: Run Node tests
        run: |
          cd $GITHUB_WORKSPACE/node
          npm install
          npm test

      - name: Run React tests
        run: |
          cd $GITHUB_WORKSPACE/react
          npm install
          npm test
      #- name: Simulate a failure # Test that the failure email is sent 
      #  run: exit 1  # This will cause the job to fail

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} ${{ job.status }}
          body: |
            Job: ${{ github.job }} in workflow: ${{ github.workflow }} of repository: ${{ github.repository }} has status: ${{ job.status }}.
          to: ${{ secrets.PERSONAL_EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}

      - name: End Timer and Calculate Duration
        id: end_timer
        run: |
          end_time=$(date +%s)
          duration=$((end_time - $(echo $start_time)))
          echo "duration=${duration}" >> $GITHUB_OUTPUT

      - name: Output end timer variable
        run: echo "Duration ${{ steps.end_timer.outputs.duration }}"

  build-angular:
    runs-on: ubuntu-latest
    needs: run-tests
    outputs:
      output1: ${{ steps.end_timer.outputs.duration }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Start Timer
        id: start_timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Build Angular app
        run: |
          cd angular
          npm install
          npm run build --prod

      - name: List contents of dist directory
        run: pwd && ls -l

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: /home/runner/work/angular-react-starter/angular-react-starter/angular/dist/angular-starter

      - name: End Timer and Calculate Duration
        id: end_timer
        run: |
          end_time=$(date +%s)
          duration=$((end_time - $(echo $start_time)))
          echo "duration=${duration}" >> $GITHUB_OUTPUT

      - name: Output end timer variable
        run: echo "Duration ${{ steps.end_timer.outputs.duration }}"

  docker:
    runs-on: ubuntu-latest
    needs: build-angular
    outputs:
      output1: ${{ steps.end_timer.outputs.duration }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Start Timer
        id: start_timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: List directory contents
        run: ls -la
        
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: angular/dist/angular-starter

      - name: Build Docker image
        run: |
          cd angular && docker build -t angular-starter .
      
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Tag Docker image
        run: |
            docker tag angular-starter ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):$(echo "${{ github.ref_name }}" | tr '/' '-')
      - name: Push Docker image
        run: |
            docker push ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):$(echo "${{ github.ref_name }}" | tr '/' '-')
      - name: End Timer and Calculate Duration
        id: end_timer
        run: |
          end_time=$(date +%s)
          duration=$((end_time - $(echo $start_time)))
          echo "duration=${duration}" >> $GITHUB_OUTPUT

      - name: Output end timer variable
        run: echo "Duration ${{ steps.end_timer.outputs.duration }}"

  notify:
    runs-on: ubuntu-latest
    needs:
      - run-tests 
      - build-angular 
      - docker  
    if: success()  
    steps:
      - name: Calculate Total Runtime
        id: calculate_runtime
        run: |
          RUN_TESTS_DURATION=${{ needs.run-tests.outputs.output1 }}
          BUILD_ANGULAR_DURATION=${{ needs.build-angular.outputs.output1 }}
          DOCKER_DURATION=${{ needs.docker.outputs.output1 }}

          TOTAL_RUNTIME=$((RUN_TESTS_DURATION + BUILD_ANGULAR_DURATION + DOCKER_DURATION))

          echo "total_runtime=${TOTAL_RUNTIME}" >> $GITHUB_ENV

      - name: Send mail on success with runtimes
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Angular Actions Pipeline Completed Successfully"
          body: |
            The Angular Actions pipeline has completed successfully!

            Job Runtimes (in seconds):
            --------------------------
            Run Tests Duration : ${{ needs.run-tests.outputs.output1 }}
            Build Angular Duration : ${{ needs.build-angular.outputs.output1 }}
            Docker Build Duration : ${{ needs.docker.outputs.output1 }}

            Total Runtime : ${{ env.total_runtime }} seconds.

            Thank you!
          
          to: ${{ secrets.PERSONAL_EMAIL_USERNAME }}
          from: "${{ secrets.EMAIL_USERNAME }}"
